name: JouTakTemplate
version: '${project.version}'
main: org.joutak.joutaktemplate.JouTakTemplate
api-version: '1.20'
commands:
  playertime:
    description: Показывает время входа и разницу
    usage: /playertime